version: '3.3'

services:
  db:
    image: mariadb:10.3.9
    restart: 'on-failure'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - './data:/var/lib/mysql'


  webapp:
    restart: always
    build:
      context: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    command: [ "python3", "./src/manage.py", "runserver", "0.0.0.0:8000" ]
    environment:
      - DB_BACKEND=${DB_BACKEND}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
